
"""Initial MariaDB migration setup"""

# revision identifiers, used by Alembic.
revision = '20616d573acc'
down_revision = '031fea7b06a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        pass  # TODO: Replace with manual Alembic op commands or op.execute('SQL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        pass  # TODO: Replace with manual Alembic op commands or op.execute('SQL')
    # ### end Alembic commands ###