"""Add UserProfile fields

Revision ID: 319f72c72035
Revises: 20616d573acc
Create Date: 2025-04-04 20:42:46.065321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '319f72c72035'
down_revision = '20616d573acc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_application', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Applied'"))
    op.alter_column('user_profile', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('job_application', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Applied'"))
    # ### end Alembic commands ###